### ISSUE TITLE
support for external data

### ISSUE THREAD

**Issue by mlubin** [kersulis/MatpowerCases.jl#16]
Could we have an option to `loadcase` to load a case file from an external location instead of the package's data folder? I can make a PR for this if it would help.
CC @dvorkinman

**Comment by kersulis** [comment]
Great idea, I'll get that working today.

**Comment by kersulis** [comment]
Should be working with fce6bea, which will be published as MatpowerCases 0.5.0 once the METADATA PR goes through.

**Comment by mlubin** [comment]
Thanks!
